# validate.yml
# Validates that Libation will build on a pull request or push to master.
---
name: validate

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  docker:
    uses: ./.github/workflows/docker.yml
    with:
      version: ${GITHUB_SHA}
      release: false
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKERHUB_TOKEN }}
